language: python
python:
- '2.7'
env:
  - WORKSHOP_NAME=example-workshop
  - WORKSHOP_NAME=dcmetromap
  - WORKSHOP_NAME=ansible-for-devops
services:
- docker
install:
- pip install -r requirements.txt
script:
- bash hack/run.sh ${WORKSHOP_NAME} local
deploy:
  provider: script
  script: bash hack/build.sh ${WORKSHOP_NAME} quay
  on:
    branch: master
